site_name: ckanext-cwbi-harvesters
site_url: https://github.com/cwbi/ckanext-cwbi-harvesters
#site_url: http://localhost:8000

site_description: >-
  The documentation of ckanext-cwbi-harvesters, a CKAN extension focused on
  generic harvesting workflows and ArcGIS support.


repo_name: cwbi/ckanext-cwbi-harvesters
repo_url: https://github.com/cwbi/ckanext-cwbi-harvesters

theme:
  name: material
  palette:
  - Harvester: 'harvester.md'
        icon: material/toggle-switch-off
        name: Switch to light mode

  logo: _assets/logo.png
  favicon: _assets/ckan.ico
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _js/tablesort.js

extra_css:
  - _css/extra.css

nav:
  - Home: 'index.md'
  - Getting started: 'getting-started.md'
  - Harvester: 'harvester.md'
  - Contributing: 'contributing.md'
